<script setup lang="ts">
import { computed,onMounted,reactive,ref,watch } from 'vue';
import { ElMessage } from 'element-plus';
import { useRoute } from 'vue-router';
import { customerCenterApi as api } from '@/api/customer-center';
import { useAuthStore } from '@/stores/auth';
const route=useRoute(),auth=useAuthStore(); const loading=ref(false),rows=ref<Record<string,any>[]>([]),customers=ref<Record<string,any>[]>([]),types=ref<Record<string,any>[]>([]),groups=ref<Record<string,any>[]>([]),tags=ref<Record<string,any>[]>([]); const keyword=ref(''),dialog=ref(false),selectedCustomer=ref(''),detail=ref<any>(null);
const mode=computed(()=>String(route.meta.customerMode??'archives')); const titles:any={archives:'客户档案',types:'客户类型',groups:'集团管理',tags:'客户标签',dashboard:'客户看板',orders:'下单情况',history:'订货历史',agreements:'协议价',credit:'信用管理'};
const form=reactive<any>({customer_name:'',contact_name:'',phone:'',address:'',account_name:'',password:'',customer_type_id:'',group_id:'',level_id:'',delivery_region_id:'',salesperson_id:'',tag_ids:[],status:'ACTIVE',credit_limit:0,credit_days:0,credit_payment_enabled:false,discount_rate:1});
async function load(){loading.value=true;try{[customers.value,types.value,groups.value,tags.value]=await Promise.all([api.customers({keyword:keyword.value||undefined}),api.types(),api.groups(),api.tags()]);if(mode.value==='archives')rows.value=customers.value;if(mode.value==='types')rows.value=types.value;if(mode.value==='groups')rows.value=groups.value;if(mode.value==='tags')rows.value=tags.value;if(mode.value==='agreements')rows.value=await api.agreements();const first=customers.value[0];if(['dashboard','orders','history','credit'].includes(mode.value)&&first){selectedCustomer.value ||= String(first.id);await loadCustomerMode();}}finally{loading.value=false;}}
async function loadCustomerMode(){if(!selectedCustomer.value)return;if(mode.value==='dashboard')detail.value=await api.dashboard(selectedCustomer.value);if(mode.value==='orders')rows.value=await api.orders(selectedCustomer.value);if(mode.value==='history')rows.value=await api.history(selectedCustomer.value);if(mode.value==='credit')rows.value=[await api.credit(selectedCustomer.value)];}
function open(row?:any){Object.assign(form,{customer_name:row?.customer_name??'',contact_name:row?.contact_name??'',phone:row?.phone??'',address:row?.address??'',account_name:row?.account_name??'',password:'',customer_type_id:row?.customer_type_id??'',group_id:row?.group_id??'',tag_ids:row?.tags?.map((x:any)=>x.id)??[],status:row?.status??'ACTIVE',credit_limit:Number(row?.credit_limit??0),credit_days:Number(row?.credit_days??0),credit_payment_enabled:Boolean(row?.credit_enabled),discount_rate:Number(row?.discount_rate??1),id:row?.id??null});dialog.value=true;}
async function edit(row:any){open(await api.customer(String(row.id)));}
async function save(){await api.saveCustomer(form.id,{...form,customer_type_id:form.customer_type_id||undefined,group_id:form.group_id||undefined,password:form.password||undefined});ElMessage.success('客户档案已保存');dialog.value=false;await load();}
async function createConfig(){if(mode.value==='types')await api.saveType({name:'新客户类型',default_discount:1,default_credit_days:0});if(mode.value==='groups')await api.saveGroup({group_name:`新集团${Date.now().toString().slice(-4)}`,contact_name:'联系人',phone:'13800000000',address:'待完善'});if(mode.value==='tags')await api.saveTag({tag_name:`新标签${Date.now().toString().slice(-4)}`,color:'#409EFF',sort:99});ElMessage.success('已新增，可在后续编辑中维护');await load();}
watch(()=>route.fullPath,load);onMounted(load);
</script>
<template><section><div class="page-heading"><div><p class="eyebrow">CUSTOMER CENTER</p><h1>{{titles[mode]}}</h1></div><ElButton v-if="mode==='archives'&&auth.hasPermission('customer.center.manage')" type="primary" @click="open()">新增客户</ElButton><ElButton v-else-if="['types','groups','tags'].includes(mode)&&auth.hasPermission('customer.config.manage')" type="primary" @click="createConfig">新增</ElButton></div>
<div class="management-card"><div style="display:flex;gap:12px;margin-bottom:18px"><ElInput v-if="mode==='archives'" v-model="keyword" placeholder="客户名称/账号/编码/联系人/手机号" clearable style="width:320px" @keyup.enter="load"/><ElSelect v-if="['dashboard','orders','history','credit'].includes(mode)" v-model="selectedCustomer" filterable style="width:260px" @change="loadCustomerMode"><ElOption v-for="c in customers" :key="c.id" :label="c.customer_name" :value="String(c.id)"/></ElSelect><ElButton @click="load">查询</ElButton></div>
<ElRow v-if="mode==='dashboard'&&detail" :gutter="16"><ElCol :span="6"><ElStatistic title="累计采购金额" :value="Number(detail.summary?.purchase_amount||0)" prefix="¥"/></ElCol><ElCol :span="6"><ElStatistic title="累计订单" :value="Number(detail.summary?.order_count||0)"/></ElCol><ElCol :span="6"><ElStatistic title="平均客单价" :value="Number(detail.summary?.average_order_amount||0)" prefix="¥"/></ElCol><ElCol :span="6"><ElStatistic title="售后次数" :value="Number(detail.summary?.after_sale_count||0)"/></ElCol></ElRow>
<ElTable v-else v-loading="loading" :data="rows"><template v-if="mode==='archives'"><ElTableColumn prop="account_name" label="客户账号"/><ElTableColumn prop="customer_no" label="客户编码" width="170"/><ElTableColumn prop="customer_name" label="客户名称"/><ElTableColumn prop="contact_name" label="联系人"/><ElTableColumn prop="phone" label="电话"/><ElTableColumn prop="region_name" label="区域"/><ElTableColumn prop="customer_type" label="类型"/><ElTableColumn prop="salesperson_name" label="业务员"/><ElTableColumn prop="credit_limit" label="信用额度"/><ElTableColumn prop="tags" label="标签"/><ElTableColumn label="操作"><template #default="{row}"><ElButton link @click="edit(row)">详情/编辑</ElButton></template></ElTableColumn></template>
<template v-else-if="mode==='types'"><ElTableColumn prop="name" label="名称"/><ElTableColumn prop="default_discount" label="默认折扣"/><ElTableColumn prop="default_credit_days" label="默认账期"/><ElTableColumn prop="status" label="状态"/></template><template v-else-if="mode==='groups'"><ElTableColumn prop="group_name" label="集团"/><ElTableColumn prop="contact_name" label="联系人"/><ElTableColumn prop="phone" label="电话"/><ElTableColumn prop="address" label="地址"/><ElTableColumn prop="customer_count" label="旗下客户"/></template><template v-else-if="mode==='tags'"><ElTableColumn prop="tag_name" label="标签"/><ElTableColumn prop="color" label="颜色"/><ElTableColumn prop="sort" label="排序"/><ElTableColumn prop="status" label="状态"/></template><template v-else><ElTableColumn v-for="key in Object.keys(rows[0]||{}).slice(0,10)" :key="key" :prop="key" :label="key"/></template></ElTable></div>
<ElDialog v-model="dialog" title="客户档案" width="780"><ElForm label-width="100px"><ElDivider content-position="left">基础信息</ElDivider><ElRow :gutter="16"><ElCol :span="12"><ElFormItem label="客户账号"><ElInput v-model="form.account_name"/></ElFormItem></ElCol><ElCol :span="12"><ElFormItem label="登录密码"><ElInput v-model="form.password" type="password"/></ElFormItem></ElCol><ElCol :span="12"><ElFormItem label="客户名称"><ElInput v-model="form.customer_name"/></ElFormItem></ElCol><ElCol :span="12"><ElFormItem label="客户类型"><ElSelect v-model="form.customer_type_id" style="width:100%"><ElOption v-for="x in types" :key="x.id" :label="x.name" :value="String(x.id)"/></ElSelect></ElFormItem></ElCol><ElCol :span="12"><ElFormItem label="联系人"><ElInput v-model="form.contact_name"/></ElFormItem></ElCol><ElCol :span="12"><ElFormItem label="联系电话"><ElInput v-model="form.phone"/></ElFormItem></ElCol></ElRow><ElDivider content-position="left">收货与财务</ElDivider><ElFormItem label="收货地址"><ElInput v-model="form.address"/></ElFormItem><ElRow :gutter="16"><ElCol :span="12"><ElFormItem label="信用额度"><ElInputNumber v-model="form.credit_limit" :min="0"/></ElFormItem></ElCol><ElCol :span="12"><ElFormItem label="账期天数"><ElInputNumber v-model="form.credit_days" :min="0"/></ElFormItem></ElCol><ElCol :span="12"><ElFormItem label="账期支付"><ElSwitch v-model="form.credit_payment_enabled"/></ElFormItem></ElCol><ElCol :span="12"><ElFormItem label="客户折扣"><ElInputNumber v-model="form.discount_rate" :min="0.01" :max="1" :step="0.01"/></ElFormItem></ElCol></ElRow><ElFormItem label="客户标签"><ElSelect v-model="form.tag_ids" multiple style="width:100%"><ElOption v-for="x in tags" :key="x.id" :label="x.tag_name" :value="String(x.id)"/></ElSelect></ElFormItem></ElForm><template #footer><ElButton @click="dialog=false">取消</ElButton><ElButton type="primary" @click="save">保存</ElButton></template></ElDialog></section></template>
