<script setup lang="ts">
import{onLoad}from'@dcloudio/uni-app';import{computed,ref}from'vue';import{afterSalesApi,type AfterSaleReason}from'@/api/after-sales';import{purchaseOrderApi,type CustomerOrder}from'@/api/orders';
type Selection={selected:boolean;value:number};type Uploaded={media_type:'IMAGE'|'VIDEO';url:string;thumbnail_url:string|null;sort:number};
const order=ref<CustomerOrder|null>(null),reasons=ref<AfterSaleReason[]>([]),reasonId=ref(''),description=ref(''),selection=ref<Record<string,Selection>>({}),media=ref<Uploaded[]>([]),loading=ref(true),submitting=ref(false),uploading=ref(false);
const selectedItems=computed(()=>order.value?.items.filter(i=>selection.value[i.id]?.selected)??[]);const estimate=computed(()=>selectedItems.value.reduce((sum,i)=>{const price=Number(i.sale_type==='WEIGHT'?(i.net_weight_unit_price??i.gross_weight_unit_price??i.final_unit_price??i.unit_price):(i.final_unit_price??i.unit_price));return sum+(selection.value[i.id]?.value??0)*price},0).toFixed(2));
function maxValue(item:CustomerOrder['items'][number]){return Number(item.sale_type==='PIECE'?(item.actual_quantity??item.planned_quantity??0):(item.actual_net_weight??item.actual_weight??item.planned_weight??0))}
function afterSaleUnit(item:CustomerOrder['items'][number]){return item.sale_type==='WEIGHT'?(item.weight_unit??'斤'):item.unit}
async function chooseImages(){const current=media.value.filter(m=>m.media_type==='IMAGE').length;if(current>=6)return uni.showToast({title:'最多上传6张图片',icon:'none'});uni.chooseImage({count:6-current,success:async result=>{uploading.value=true;try{for(const path of result.tempFilePaths){const r=await afterSalesApi.uploadImage(path);media.value.push({media_type:'IMAGE',url:r.url,thumbnail_url:r.thumbnail_url,sort:media.value.length})}}catch(e){uni.showToast({title:(e as{message?:string}).message??'图片上传失败',icon:'none'})}finally{uploading.value=false}}})}
async function chooseVideo(){if(media.value.filter(m=>m.media_type==='VIDEO').length>=3)return uni.showToast({title:'最多上传3个视频',icon:'none'});uni.chooseVideo({sourceType:['album','camera'],compressed:false,maxDuration:60,success:async result=>{uploading.value=true;try{const r=await afterSalesApi.uploadVideo(result.tempFilePath);media.value.push({media_type:'VIDEO',url:r.url,thumbnail_url:r.thumbnail_url,sort:media.value.length})}catch(e){uni.showToast({title:(e as{message?:string}).message??'视频上传失败',icon:'none'})}finally{uploading.value=false}}})}
function removeMedia(index:number){media.value.splice(index,1)}
async function submit(){if(!reasonId.value)return uni.showToast({title:'请选择售后原因',icon:'none'});if(!selectedItems.value.length)return uni.showToast({title:'请选择售后商品',icon:'none'});if(selectedItems.value.some(i=>(selection.value[i.id]?.value??0)<=0))return uni.showToast({title:'请填写有效数量或重量',icon:'none'});submitting.value=true;try{const result=await afterSalesApi.create({order_id:order.value!.id,reason_id:reasonId.value,description:description.value,items:selectedItems.value.map(i=>({order_item_id:i.id,...(i.sale_type==='PIECE'?{quantity:selection.value[i.id]!.value}:{requested_weight:selection.value[i.id]!.value})})),media:media.value});uni.showToast({title:'售后申请已提交',icon:'success'});setTimeout(()=>uni.redirectTo({url:`/pages/after-sale/detail?id=${result.id}`}),500)}catch(e){uni.showToast({title:(e as{message?:string}).message??'提交失败',icon:'none'})}finally{submitting.value=false}}
onLoad(async o=>{try{const id=String(o?.order_id??'');[order.value,reasons.value]=await Promise.all([purchaseOrderApi.order(id),afterSalesApi.reasons()]);for(const item of order.value.items)selection.value[item.id]={selected:false,value:item.sale_type==='PIECE'?1:Math.min(1,maxValue(item))}}catch(e){uni.showToast({title:(e as{message?:string}).message??'申请页加载失败',icon:'none'})}finally{loading.value=false}})
</script>
<template><view v-if="order" class="page"><view class="panel"><text class="title">选择售后商品</text><view v-for="item in order.items" :key="item.id" class="item"><checkbox :checked="selection[item.id]?.selected" @click="selection[item.id]!.selected=!selection[item.id]!.selected"/><view class="info"><strong>{{item.product_name}}</strong><text>{{item.sku_name}} · 已购 {{maxValue(item)}} {{afterSaleUnit(item)}}</text><text>退款单价 ¥{{item.sale_type==='WEIGHT'?(item.net_weight_unit_price??item.gross_weight_unit_price??item.final_unit_price??item.unit_price):(item.final_unit_price??item.unit_price)}}/{{afterSaleUnit(item)}}</text></view><view><text>{{item.sale_type==='PIECE'?'售后数量':'申请缺失重量'}}</text><input v-model.number="selection[item.id]!.value" type="digit" :max="maxValue(item)" :disabled="!selection[item.id]?.selected"/></view></view></view><view class="panel"><text class="title">问题说明</text><picker :range="reasons" range-key="name" @change="reasonId=reasons[Number($event.detail.value)]?.id||''"><view class="picker">{{reasons.find(r=>r.id===reasonId)?.name||'请选择售后原因'}} ›</view></picker><textarea v-model="description" maxlength="2000" placeholder="请描述缺重、品质或破损情况"/></view><view class="panel"><text class="title">图片和视频凭证</text><text class="hint">最多6张图片、3个MP4视频</text><view class="actions"><button size="mini" :loading="uploading" @click="chooseImages">上传图片</button><button size="mini" :loading="uploading" @click="chooseVideo">上传视频</button></view><view class="media"><view v-for="(m,i) in media" :key="m.url"><image v-if="m.media_type==='IMAGE'" :src="m.thumbnail_url||m.url" mode="aspectFill"/><video v-else :src="m.url" :poster="m.thumbnail_url||''"/><text @click="removeMedia(i)">×</text></view></view></view><view class="bottom"><view><text>预计退款</text><strong>¥{{estimate}}</strong></view><button :loading="submitting" @click="submit">提交售后申请</button></view></view><view v-else class="loading">{{loading?'正在加载…':'订单不可申请售后'}}</view></template>
<style scoped lang="scss">.page{min-height:100vh;padding:20rpx 20rpx 150rpx;background:#f4f6f3}.panel{margin-bottom:18rpx;padding:25rpx;border-radius:20rpx;background:#fff}.title{display:block;margin-bottom:16rpx;font-size:28rpx;font-weight:800}.item{display:flex;padding:20rpx 0;border-top:1rpx solid #edf0ed;align-items:center;gap:12rpx}.info{min-width:0;flex:1}.info strong,.info text,.item>view:last-child text{display:block}.info strong{font-size:24rpx}.info text,.item>view:last-child text,.hint{margin-top:5rpx;color:#7d8981;font-size:19rpx}.item input{width:110rpx;margin-top:8rpx;padding:10rpx;border-radius:10rpx;background:#f3f5f3;text-align:center}.picker,textarea{padding:20rpx;border-radius:14rpx;background:#f5f7f5;font-size:23rpx}textarea{box-sizing:border-box;width:100%;height:180rpx;margin-top:14rpx}.actions{display:flex;margin-top:14rpx;gap:12rpx}.actions button{margin:0}.media{display:flex;flex-wrap:wrap;margin-top:14rpx;gap:12rpx}.media view{position:relative}.media image,.media video{width:180rpx;height:160rpx;border-radius:12rpx}.media view>text{position:absolute;top:-8rpx;right:-8rpx;display:grid;width:38rpx;height:38rpx;border-radius:50%;color:#fff;background:#d95740;place-items:center}.bottom{position:fixed;right:0;bottom:0;left:0;display:flex;padding:18rpx 22rpx calc(18rpx + env(safe-area-inset-bottom));background:#fff;align-items:center;justify-content:space-between}.bottom text,.bottom strong{display:block}.bottom text{color:#7b857f;font-size:20rpx}.bottom strong{color:#d95740;font-size:32rpx}.bottom button{width:300rpx;margin:0;color:#413500;background:#f9c800;font-weight:800}.loading{padding:220rpx 20rpx;text-align:center}</style>
