<script setup lang="ts">
import { computed,onMounted,reactive,ref,watch } from 'vue';import { useRoute } from 'vue-router';import { ElMessage } from 'element-plus';
import { biApi,type BiData } from '@/api/bi';import AppPagination from '@/components/AppPagination.vue';import BiChart from '@/components/reports/BiChart.vue';import { useAuthStore } from '@/stores/auth';
const route=useRoute(),auth=useAuthStore(),loading=ref(false),data=ref<BiData|null>(null),dateRange=ref<[string,string]|[]>([]),chartType=ref<'area'|'bar'|'donut'>('area');
const query=reactive({date_from:'',date_to:'',keyword:'',brand:'',category_id:'',purchase_manager_id:'',delivery_region_id:'',customer_type_id:'',top:10,page:1,page_size:20});
const type=computed(()=>String(route.meta.biType??'inventory')),title=computed(()=>String(route.meta.title??'BI报表').split('/').pop());
const labels:Record<string,string>={stock_value:'库存金额',stock_cost:'库存成本',stock_quantity:'库存数量',turnover_rate:'库存周转率',turnover_days:'库存周转天数',warning_count:'库存预警',near_out_count:'即将售空',expiring_count:'即将过期',delivery_count:'配送单数量',completion_rate:'配送完成率',average_minutes:'平均配送时长(分)',on_time_rate:'及时率',delivery_cost:'配送成本',exception_count:'配送异常',failed_count:'配送失败',today_income:'今日收入',month_income:'本月收入',today_profit:'今日利润',month_profit:'本月利润',margin_rate:'毛利率',receivables:'应收账款',payables:'应付账款',refund_amount:'退款金额',refund_rate:'退款率',unpaid_orders:'未收款订单',sales_amount:'销售额',profit_amount:'利润',salesperson_count:'业务员数',customer_count:'客户数',debt_amount:'客户欠款',repeat_customers:'复购客户',sales_quantity:'销售数量',product_count:'商品数',purchase_amount:'采购金额',purchase_quantity:'采购数量',purchase_cost:'采购成本',average_price:'采购均价',supplier_count:'供应商数',return_amount:'退货金额'};
const summaryCards=computed(()=>Object.entries(data.value?.summary??{}).map(([key,value])=>({key,label:labels[key]??key,value:Number(value??0)})));
const columns=computed(()=>Object.keys(data.value?.items?.[0]??{}));const rankings=computed(()=>Object.entries(data.value?.rankings??{}).filter(([,rows])=>rows.length).slice(0,2));
function date(offset:number){const d=new Date(Date.now()+offset*86400000);return d.toISOString().slice(0,10);}function preset(offset:number){query.date_from=date(offset);query.date_to=date(0);dateRange.value=[query.date_from,query.date_to];query.page=1;void load();}function changeDates(v:[string,string]|null){dateRange.value=v??[];query.date_from=v?.[0]??'';query.date_to=v?.[1]??'';query.page=1;}
async function load(){loading.value=true;try{data.value=await biApi.report(type.value,query);}catch{ElMessage.error('报表加载失败或当前角色无权访问');}finally{loading.value=false;}}function page(p:number,size:number){query.page=p;query.page_size=size;void load();}
async function exportFile(format:'xlsx'|'csv'|'pdf',scope:'page'|'filtered'|'all'='filtered'){await biApi.export(type.value,format,{...query,scope});ElMessage.success(`${format.toUpperCase()} 导出完成`);}function print(){window.print();}
watch(type,()=>{query.page=1;void load();});onMounted(()=>preset(-29));
</script>
<template><section class="bi-report" v-loading="loading"><div class="page-heading"><div><p class="eyebrow">BUSINESS INTELLIGENCE</p><h1>{{title}}</h1><p>数据实时来源于业务数据库 · 60秒缓存</p></div><div class="export-actions"><ElDropdown v-if="auth.hasPermission('bi.report.export')" @command="(c:string)=>exportFile(c as any)"><ElButton type="primary">导出报表⌄</ElButton><template #dropdown><ElDropdownMenu><ElDropdownItem command="xlsx">导出 Excel</ElDropdownItem><ElDropdownItem command="csv">导出 CSV</ElDropdownItem><ElDropdownItem command="pdf">导出 PDF</ElDropdownItem></ElDropdownMenu></template></ElDropdown><ElButton @click="print">打印</ElButton></div></div>
  <div class="filters"><ElButtonGroup><ElButton @click="preset(0)">今日</ElButton><ElButton @click="preset(-1)">昨日</ElButton><ElButton @click="preset(-6)">本周</ElButton><ElButton @click="preset(-29)">本月</ElButton></ElButtonGroup><ElDatePicker :model-value="dateRange" type="daterange" value-format="YYYY-MM-DD" start-placeholder="开始日期" end-placeholder="结束日期" @update:model-value="changeDates"/><ElInput v-model="query.keyword" clearable placeholder="搜索商品/客户/人员" style="width:220px" @keyup.enter="load"/><ElInput v-if="type==='products'" v-model="query.brand" clearable placeholder="品牌" style="width:120px"/><ElSelect v-model="query.top" style="width:110px"><ElOption v-for="n in [10,20,50]" :key="n" :label="`TOP ${n}`" :value="n"/></ElSelect><ElButton type="primary" @click="load">查询</ElButton></div>
  <div class="metrics"><article v-for="x in summaryCards" :key="x.key"><span>{{x.label}}</span><strong>{{x.value.toLocaleString('zh-CN',{maximumFractionDigits:2})}}</strong></article></div>
  <div class="chart-grid"><article class="panel"><div class="panel-head"><div><h3>经营趋势</h3><small>{{data?.date_range.from}} 至 {{data?.date_range.to}}</small></div><ElRadioGroup v-model="chartType" size="small"><ElRadioButton value="area">面积</ElRadioButton><ElRadioButton value="bar">柱状</ElRadioButton><ElRadioButton value="donut">环形</ElRadioButton></ElRadioGroup></div><BiChart :rows="data?.trend??[]" :type="chartType"/></article><article v-for="([key,rows],index) in rankings" :key="key" class="panel rank-panel"><div class="panel-head"><div><h3>{{index===0?'核心排行榜':'经营结构'}}</h3><small>按当前筛选条件统计</small></div></div><BiChart :rows="rows" :type="index===0?'ranking':'donut'"/></article></div>
  <div class="management-card"><div class="panel-head"><div><h3>统计明细</h3><small>共 {{data?.pagination.total??0}} 条真实业务记录</small></div></div><ElTable :data="data?.items??[]" height="390"><ElTableColumn v-for="key in columns" :key="key" :prop="key" :label="labels[key]??key" min-width="135" show-overflow-tooltip/></ElTable><AppPagination v-if="data" :page="data.pagination.page" :page-size="data.pagination.page_size" :total="data.pagination.total" @change="page"/></div>
</section></template>
<style scoped>.page-heading p{margin:6px 0 0;color:#78847d}.export-actions{display:flex;gap:10px}.filters{display:flex;gap:10px;align-items:center;flex-wrap:wrap;padding:16px;background:#fff;border:1px solid #e3e9e5;border-radius:14px}.metrics{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:12px;margin:14px 0}.metrics article{padding:18px;background:#fff;border:1px solid #e3e9e5;border-radius:14px}.metrics span{display:block;color:#7a867f}.metrics strong{display:block;margin-top:9px;color:#183529;font-size:26px}.chart-grid{display:grid;grid-template-columns:1.4fr .8fr .8fr;gap:14px;margin-bottom:14px}.panel{padding:18px;background:#fff;border:1px solid #e3e9e5;border-radius:15px}.panel-head{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:14px}.panel-head h3,.panel-head small{margin:0}.panel-head small{color:#89948e}.management-card{background:#fff}.rank-panel{min-width:0}@media(max-width:1450px){.metrics{grid-template-columns:repeat(4,1fr)}.chart-grid{grid-template-columns:1fr 1fr}.chart-grid>.panel:first-child{grid-column:1/-1}}@media(max-width:900px){.metrics{grid-template-columns:repeat(2,1fr)}.chart-grid{grid-template-columns:1fr}.chart-grid>.panel:first-child{grid-column:auto}}@media print{.filters,.export-actions,.admin-sidebar,.admin-header{display:none!important}.bi-report{background:#fff}.management-card{break-before:page}}</style>
