<script setup lang="ts">
import { computed,onMounted,reactive,ref,watch } from 'vue';import { useRoute } from 'vue-router';import { reportsApi,type ReportData } from '@/api/reports';import AppPagination from '@/components/AppPagination.vue';import ReportTrend from '@/components/reports/ReportTrend.vue';import { useAuthStore } from '@/stores/auth';
const route=useRoute(),auth=useAuthStore(),loading=ref(false),data=ref<ReportData|null>(null);
const query=reactive({date_from:'',date_to:'',keyword:'',page:1,page_size:20});const dateRange=ref<[string,string]|[]>([]);
const type=computed(()=>String(route.meta.reportType??'business'));const title=computed(()=>String(route.meta.title??'报表中心').split('/').pop());
const presets=[['今日',0],['昨日',-1],['本周',-6],['本月',-29]] as const;
function date(days:number){const d=new Date(Date.now()+days*86400000);return d.toISOString().slice(0,10);}function preset(days:number){query.date_to=days===-1?date(-1):date(0);query.date_from=date(days);dateRange.value=[query.date_from,query.date_to];query.page=1;void load();}function changeDates(value:[string,string]|null){dateRange.value=value??[];query.date_from=value?.[0]??'';query.date_to=value?.[1]??'';query.page=1;}
async function load(){loading.value=true;try{data.value=await reportsApi.get(type.value,query);}finally{loading.value=false;}}
function page(page:number,size:number){query.page=page;query.page_size=size;void load();}
const cards=computed(()=>{const s=data.value?.summary??{};return type.value==='purchases'?[['采购金额',s.purchase_amount],['采购数量',s.purchase_quantity],['退货金额',s.return_amount],['供应商数',s.supplier_count]]:[['订单笔数',s.order_count],['退单笔数',s.return_count],['下单客户',s.customer_count],['下单金额',s.order_amount],['退款金额',s.refund_amount],['实际金额',s.actual_amount],['成本',s.cost_amount],['利润',s.profit_amount]];});
const columns=computed(()=>Object.keys(data.value?.items?.[0]??{}));watch(type,()=>{query.page=1;void load();});onMounted(()=>{preset(-29);});
const primaryRanking=computed<Record<string,any>[]>(()=>Object.values(data.value?.rankings??{})[0]??[]);
</script>
<template><section class="report-page" v-loading="loading"><div class="page-heading"><div><p class="eyebrow">REPORT CENTER</p><h1>{{title}}</h1></div><ElButton v-if="auth.hasPermission('report.export')" @click="reportsApi.export(type,query)">导出Excel</ElButton></div><div class="report-filter"><ElButtonGroup><ElButton v-for="x in presets" :key="x[0]" @click="preset(x[1])">{{x[0]}}</ElButton></ElButtonGroup><ElDatePicker :model-value="dateRange" type="daterange" value-format="YYYY-MM-DD" start-placeholder="开始日期" end-placeholder="结束日期" @update:model-value="changeDates"/><ElInput v-model="query.keyword" clearable placeholder="商品/客户/供应商搜索" style="width:240px" @keyup.enter="load"/><ElButton type="primary" @click="load">查询</ElButton></div><div class="metric-grid"><article v-for="c in cards" :key="c[0]"><span>{{c[0]}}</span><strong>{{Number(c[1]??0).toLocaleString('zh-CN',{maximumFractionDigits:2})}}</strong></article></div><div class="report-grid"><article class="chart-card"><h3>趋势分析</h3><ReportTrend :rows="data?.trend??[]"/></article><article class="chart-card"><h3>TOP 10 排行</h3><div class="ranking"><div v-for="(x,i) in primaryRanking.slice(0,10)" :key="i"><b>{{i+1}}</b><span>{{x.label??x.name}}</span><strong>¥{{x.sales_amount??x.purchase_amount??x.value??0}}</strong></div><ElEmpty v-if="!primaryRanking.length" description="暂无排行数据"/></div></article></div><div class="management-card"><h3>统计明细</h3><ElTable :data="data?.items??[]" height="360"><ElTableColumn v-for="key in columns" :key="key" :prop="key" :label="key" min-width="130" show-overflow-tooltip/></ElTable><AppPagination v-if="data" :page="data.pagination.page" :page-size="data.pagination.page_size" :total="data.pagination.total" @change="page"/></div></section></template>
<style scoped>.report-filter{display:flex;gap:12px;align-items:center;padding:18px;background:#fff;border:1px solid #e2e8e4;border-radius:14px}.metric-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:16px 0}.metric-grid article,.chart-card{background:#fff;border:1px solid #e4eae6;border-radius:14px;padding:20px}.metric-grid span{color:#718078}.metric-grid strong{display:block;margin-top:10px;font-size:30px}.report-grid{display:grid;grid-template-columns:1.35fr .65fr;gap:14px;margin-bottom:14px}.chart-card h3,.management-card h3{margin:0 0 16px}.ranking>div{display:flex;gap:10px;align-items:center;padding:9px;border-bottom:1px solid #edf1ee}.ranking b{display:grid;width:24px;height:24px;border-radius:7px;background:#e8f5ec;color:#16803b;place-items:center}.ranking span{flex:1}.ranking strong{font-size:12px}@media(max-width:1200px){.metric-grid{grid-template-columns:repeat(2,1fr)}.report-grid{grid-template-columns:1fr}}</style>
